version: '3.8'

volumes:
  postgres_data_prod:
  postgres_data_prod_backups:
  traefik_prod:
  static_prod:
  media_prod:

services:
  traefik:
    restart: on-failure
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--log.level=DEBUG"
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.miq.localhost`)"
      - "traefik.http.routers.dashboard.tls=false"
    depends_on:
      - web

  web:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile.prod
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 config.wsgi'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py collectstatic --no-input; gunicorn --access-logfile - --bind 0.0.0.0:80 config.wsgi'
    expose:
      - 80
    volumes:
      - static_prod:/home/app/web/static
      - media_prod:/home/app/web/media
    environment:
      - DEBUG=False
      - PREVIEW=False
      - DATABASE_URL=postgresql://pguser:pgpwd@db:5432/pgdb
      - DJANGO_ALLOWED_HOSTS=.miq.localhost,
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.miq.localhost`)"
  
  db:
    restart: on-failure
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/:Z
      - postgres_data_prod_backups:/backups:z
    expose:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_DB=pgdb

  nginx:
    restart: on-failure
    build: ./nginx
    environment:
      - NGINX_HOST=nginx.docker.localhost
    volumes:
      - static_prod:/home/app/web/static
      - media_prod:/home/app/web/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - traefik
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.rule=Host(`django.miq.localhost`) && PathPrefix(`/static`) || Host(`django.miq.localhost`) && PathPrefix(`/media`)"
