FROM node:19-alpine3.16 as base

RUN apk add --no-cache python3 py3-pip python3-dev build-base libffi-dev openssl-dev && \
    pip3 install --upgrade pip && \
    apk del build-base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
